### ISSUE TITLE
Moo 2.x vs. Moo::Lax

### ISSUE THREAD

**Issue by ggl** [preaction/Statocles#281]
Moo 2.x does away with fatal errors and other checks from strictures to in modules using  Moo or Moo::Role. So Moo::Lax is no longer needed.

**Comment by preaction** [comment]
Sounds good to me.

https://github.com/preaction/Statocles/blob/master/lib/Statocles/Base.pm#L42-L50
https://github.com/preaction/Statocles/blob/master/dist.ini#L102

All we have to do is change those two and run the tests. If they pass, we're done!

If you want to try it, go ahead. Otherwise, I'll do this before the next release (I've been releasing weekly these days).
