### ISSUE TITLE
found character that cannot start any token

### ISSUE THREAD

**Issue by hanleilei** [preaction/Statocles#394]
Could you tell me what does this message indicate?

**Comment by preaction** [comment]
My guess is that it's coming from the YAML parser (I found a mention on this StackOverflow post: http://stackoverflow.com/questions/4772274/the-problem-found-a-tab-character-that-violate-intendation)

That thread seems to indicate you might have a tab character instead of spaces. YAML doesn't allow tabs for indentation as far as I know.

If that doesn't fix it, could you give the entire error message (if you can, install the "Devel::Confess" module and run with the `PERL5OPT="-d:Confess"` environment variable) and your entire config file so I can reproduce the issue?

At the very least, it seems like we need to handle configuration loading issues better.
