### ISSUE TITLE
Missing `static` directory causes random breakage

### ISSUE THREAD

**Issue by kentfredric** [preaction/Statocles#421]
I was cleaning up stuff in `master` in transitioning to statocles, and I ended up `rming` that directory from my source tree.

So when I switched back to the "source" branch,

```
coercion for "store" failed: Store path '/home/kent/perl/kentfredric.github.io-statocles/static' does not exist at /home/kent/perl5/perlbrew/perls/5.22.1-nossp-sdbm-nopmc/lib/site_perl/5.22.1/Statocles/Store.pm line 61.
```

I just needed to `mkdir static/` again for pain to go away.

**Comment by preaction** [comment]
Yeah, I've gotten bit in different ways by this (if the theme directory doesn't exist yet, and you want to use `statocles bundle theme` to create it, it will fail because the theme directory doesn't exist yet), so I think I'm just going to downgrade that to a warning (#414), which are shown by default.
