### ISSUE TITLE
literal q[ <"ARGV"> ] in "title:" get downcased + HTML errors occcur.

### ISSUE THREAD

**Issue by kentfredric** [preaction/Statocles#422]
```bash
EDITOR=gvim statocles blog post "Re: The Perl Jam 2: <\"ARGV\"> is evil"
```

-> 

```yaml
title: 'Re: The Perl Jam 2: <"ARGV"> is evil'
```

->

```html
<title>Re: The Perl Jam 2: <"ARGV"> is evil - KENTNL's Blog</title>
...
 <h1>Re: The Perl Jam 2: <"argv"> is evil</"argv"></h1>
```

Note the last of these says `argv` for some reason instead of `ARGV`. 

And for some reason, the content is not escaped in either place I wrote it.

Worse, the generated HTML has syntax errors.

![snapshot95](https://cloud.githubusercontent.com/assets/44790/12069604/04cde4b2-b09f-11e5-9285-fa945e51f99d.png)

**Comment by preaction** [comment]
Wow, I imagine that bug is going to be _everywhere_. These are the things that get revealed when someone else uses your code ;)

I'm guessing the lower-cased thing in the source comes from at least one of the html parsers (Mojo::DOM most likely) trying its best to parse `<"ARGV">` (and then filling in what's missing when it sees the parent tag's end), and then on output, normalizing it maybe? So, I hope that if it's just escaped properly, that should fix the whole thing.

**Comment by kentfredric** [comment]
Yeah. I just manually replaced the `<` and `>` with `&lt;` and `&gt;` and the problem went away.

**Comment by preaction** [comment]
I've fixed this, but it was a template issue, so if you've edited your theme, you'll need to apply the fixes yourself (re-running the `statocles bundle theme` is generally how I do it, and then using `git` to ensure only the right bits are changed). Also, if you do it all by hand with the above commit, you don't have to wait for the release.
