### ISSUE TITLE
Syntax highlighting and Markdown don't play well

### ISSUE THREAD

**Issue by kentfredric** [preaction/Statocles#427]
No combination of code blocks and `%= highlight` rendered a useful output.

[test.markdown.txt](https://github.com/preaction/Statocles/files/76894/test.markdown.txt)

**Comment by kentfredric** [comment]
![snapshot105](https://cloud.githubusercontent.com/assets/44790/12083841/3307bcfa-b30f-11e5-854a-5b348fe905d3.png)

**Comment by kentfredric** [comment]
[site.yml.txt](https://github.com/preaction/Statocles/files/76895/site.yml.txt)

**Comment by kentfredric** [comment]
Ugh. Yay.

```html

<pre><code>&lt;span class=&quot;hljs-keyword&quot;&gt;use&lt;/span&gt; &lt;span class=&quot;hljs-keyword&quot;&gt;strict&lt;/span&gt;;
&lt;span class=&quot;hljs-keyword&quot;&gt;use&lt;/span&gt; &lt;span class=&quot;hljs-keyword&quot;&gt;warnings&lt;/span&gt;;
&lt;span class=&quot;hljs-keyword&quot;&gt;while&lt;/span&gt;(&lt;span class=&quot;hljs-number&quot;&gt;1&lt;/span&gt;) {
  &lt;span class=&quot;hljs-function&quot;&gt;print&lt;/span&gt; &quot;&lt;span class=&quot;hljs-variable&quot;&gt;$_&lt;/span&gt;&quot;;
}
</code></pre>```

So its applying the markdown formatting *after* its highlighting it. Yay.

**Comment by preaction** [comment]
Right. Originally it was processed as a template first, then doing markdown rendering so that you could actually include markdown. Now that the `markdown` template helper is a thing, that's not actually as important anymore.

I think the difference between my tests and yours was I had to add the `<pre>` and `<code>` tags. Right now that's mostly because I couldn't decide if I wanted to do that for the user or not. If we always include a `<pre>` tag, we can't use highlight inline. Though if we generate the `<code>` tag and ensure that it's in the first column, we might be able to fix some of those issues. Whitespace will still be treated like whitespace in the HTML though, so `<pre>` needs to be added for blocks of code (wrapping the code in `<pre>` will also prevent Markdown from applying inside).

I could also in theory try to detect the indented code block and automatically add a `<pre>`.

I'm trying to avoid needing to replace all `\n` with `<br>` and all whitespace with the right number of `&nbsp;`, which just seems terrible to me.

**Comment by preaction** [comment]
Or I could come up with some heuristics of when to apply `<pre>` (code block begins with whitespace, and/or code block contains newline character perhaps), and allow overriding of those heuristics when needed (something like `%= highlight { pre => 1|0 }, perl => begin` or something).

**Comment by preaction** [comment]
Yeah. Wrapping all the highlight calls in `<pre>...</pre>` seems to fix the issue, because it stops Markdown from applying inside. But I wasn't too keen on it before, and I'm even less keen on it now. I'm going to try adding those tags automatically and see how that works...

**Comment by preaction** [comment]
Okay. I think I've found a heuristic that feels natural and addresses all the examples you posted. Give me a bit to add your examples as tests and I'll commit it.

It's pretty simple: If the code starts with more than one space, a tab, or a newline, it gets a `pre`. Using the `%= highlight Perl => begin` syntax means that the code will start with a newline, so that will get a `pre`. Doing it like `<%= highlight Perl => begin %>print()<%= end %>` doesn't start with a newline, and doesn't get a `pre`. The leading newline gets stripped from the source for convenience (otherwise it'd leave a nasty empty space on top).

I'm going to be an ass and not add the override just yet: I want to see if this feels natural, and get people to report the problem cases (which I really appreciate by the way). I do have a feeling it will boil down to people simply wanting control, and at that point, I'll add a few things:

* Set the default behavior via plugin attributes
* Override that default behavior via function arguments

**Comment by preaction** [comment]
Except my heuristic breaks on `%= highlight perl => include "test.pl"`, which I really, really want to work...

Alright. Blocks (`<pre>`) by default. Inline with argument. Attribute to change default.
