### ISSUE TITLE
`include => ` note in Syntax highlighting needs clarification

### ISSUE THREAD

**Issue by kentfredric** [preaction/Statocles#428]
1. I can't find what `include` does or where its implemented
2. It doesn't look like part of Mojolicious
3. I put a file in my blog's dir and assumed the path would be relative to that, but alas, it is not ( and there's no documentation explaining what I should assume the path to be, or how to get a path relative to my current blog if I wanted one )

**Comment by kentfredric** [comment]
Ugh. Strace indicates `cwd` is in `./theme/` when I run it.

I was hoping something like:
```
%= highlight Perl => include './blog/' . $self->path->sibling('/code_01.pl')
```
would work, but instead, that resolves to ....

```
$ROOT/theme/blog/<FULLBLOG_PATH>/code_01.pl
```
Ew.

I could use `../` but I really don't like "Rely on where we are in a mishmash of cwd() calls" being done in user code.

**Comment by kentfredric** [comment]
Wut. I'm doing something horribly wrong. The only way I can get a path is: 
```
%= highlight Perl => include $app->store->path->child($self->path->sibling('/code_01.pl'))
```

And well, that just tells me to get lost
```
Error in template: Error in template: Can not find include "{REDACTED}/{PROJECT}/blog/2016/01/01/re-the-perl-jam-2-argv-is-evil/code_01.pl" at {REDACTED}/{PERL}/Statocles/Theme.pm line 113.
```
Even though the path in question factually exists:
```
file {REDACTED}/{PROJECT}/blog/2016/01/01/re-the-perl-jam-2-argv-is-evil/code_01.pl
{REDACTED}/{PROJECT}/blog/2016/01/01/re-the-perl-jam-2-argv-is-evil/code_01.pl: a /usr/bin/env perl script, ASCII text executable
```

**Comment by preaction** [comment]
Yes, this will need to be fixed by adding the proper include dir when the content template is generated (in Statocles::Page::Document sub _render_content_template). I thought about this, and then completely failed to even try it, much less test for it...

So, to fix all this:

* [ ] Ensure the document's parent directory is in the include paths when rendering the document as a template
* [ ] Ensure that references to the `include` helper are linked, preferably to a description in the Statocles::Template object where they're implemented

**Comment by preaction** [comment]
All the includes are relative to the include dirs. Absolute paths aren't allowed. I might have had a reason for this, but I don't remember. I'll have to take a look... I could imagine some terrible things, but on the other hand, I could also imagine the user being able to aim at their own foot if they want, so perhaps there can be a flag for it...

**Comment by kentfredric** [comment]
I'm mostly just bodging with absolute paths trying to get around the existing bugs, so I wouldn't be so ready to enshrine that as a useful behaviour.

If it comes to that, you might want to have an `include_abs` function, or an `unsafe_include` function or similar so that the user knows they're potentially accessing an arbitrary path, and it should be obvious in code review.

Otherwise I'd use namespaced routing with something like

```perl
   include { relative_to => $page }, "foo.txt";
   include { relative_to => $app }, "2016/01/02/Label/foo.txt";
   include { relative_to => $site }, "etc/etc";
   include { relative_to => $template }, "etc/etc";
```

**Comment by preaction** [comment]
The unsafe include function could be a plugin even, so that it could be enabled by the site admin only if desired. There's a future plan to have a web frontend to edit Statocles sites, is mainly why it has to be optional.

And come to think of it, that error message could probably explain better what is going on (by listing the directories searched perhaps).

**Comment by kentfredric** [comment]
> so that it could be enabled by the site admin only if desired.

Agreed. I would even go as far to say as it should be missing by default, and you very much have to opt-in to get that helper =)

**Comment by preaction** [comment]
Though, I'm now pretty certain I don't do any actual checking, so "../../../../../../.." would probably work, which defeats the point of whatever safety I might've had in mind (6 months ago me obviously did not think this one through...). I also like the idea of being able to go relative to the app, so that an entire directory of pages could all reference some common element in a parent directory. But, I think people would likely try to do `include "../common.markdown"` first, so perhaps just make sure that the "safety check" doesn't allow leaving the app's root directory.
