### ISSUE TITLE
[blog] Don't poke page internal data structure

### ISSUE THREAD

**Issue by preaction** [preaction/Statocles#449]
https://github.com/preaction/Statocles/blob/master/lib/Statocles/App/Blog.pm#L335

Nothing should access a page's `_links` like this. Instead it should use `links( type => $new_link )` to add new links.

**Comment by kentfredric** [comment]
Also, the use of the word `type`, both here and in the comment on my repo is confusing.

What does `type` mean here, surely you mean `links( $key => $newlink ) or ...  there's just too much different terminology here, and it conflicts with the terminology used here: https://metacpan.org/pod/Statocles::Page#links1 

so is the literal text `type` significant? 

Because when somebody says:

    type => $x 

My brain is asking "there's a thing, and you're setting its type to x", so when you're doing anything other than that, that term is really confusing.

And if it *is* doing that, then why is it doing that? What for?

How is a "Link object" a "type" ?

**Comment by preaction** [comment]
Sorry, yes, `$key` is more appropriate. By `type` I mean what kind of resource is being linked to: A stylesheet, a script, an alternate version, a canonical version, the next page, the previous page, etc... This is closer to the `rel` attribute of the link object.
