### ISSUE TITLE
t/command/error.t fails with YAML.pm

### ISSUE THREAD

**Issue by eserte** [preaction/Statocles#460]
See this fail report: http://www.cpantesters.org/cpan/report/22b55ee2-d0ed-11e5-80f8-baa3fcd2507e

It seems that this happens if YAML::XS is absent and only YAML.pm is installed.

**Comment by preaction** [comment]
Ah. It's using YAML::Syck, because Beam::Wire uses Config::Any which uses YAML::XS, YAML::Syck, and finally YAML.pm. So I need to detect the error that Syck produces in order to tell the user what remedy they have...

The key bit of the error is: `Syck parser (line 6, column 9): syntax error at /opt/perl-5.23.7t/lib/site_perl/5.23.7/x86_64-linux-thread-multi/YAML/Syck.pm line 75.`

Config::Any was the biggest mistake I made in Beam::Wire...
