### ISSUE TITLE
Move away from GitHub

### ISSUE THREAD

**Issue by dertuxmalwieder** [preaction/Statocles#536]
Since GitHub basically [takes your rights](https://www.mirbsd.org/permalinks/wlog-10_e20170301-tg.htm) from Statocles, you might want to migrate to something else. :-)

**Comment by preaction** [comment]
IANAL, and, as far as I can tell, neither is the person you linked to, and they do not seem to bother to justify their conclusions. I read the passages, and though the language is unclear in those particular sections, their language is unambiguous in other sections: I retain all rights to my project. A contract that claims two contradictory things is not going to hold up in court, so I'm going to assume that isn't what they mean until otherwise noted.
