### ISSUE TITLE
/page/1 does not exist (404 error)

### ISSUE THREAD

**Issue by CandyAngel** [preaction/Statocles#575]
The expected URL for page 1 doesn't work (it returns 404).

This can be seen on mojolicious.io where [page 2](https://mojolicious.io/blog/page/2/) works but [page 1](https://mojolicious.io/blog/page/1/) does not.

It seems to be because the application [doesn't generate a "1" directory](https://mojolicious.io/blog/page/) to be served.

**Comment by CandyAngel** [comment]
Just thought I should note that I didn't discover this while using site itself, but rather by changing the URL directly.

**Comment by preaction** [comment]
There is no page 1 because page 1 is in the index page. It's a bigger problem to have the same content served at two different URLs (search engines _hate_ that), so Statocles instead just moves `/<app>/page/1/index.html` to `/<app>/index.html`. It's marginally weird to have a page "2" but no page "1", but I felt it weirder to call something page "1" when it's clearly the second page of content.

So, nothing really I can fix here 😄
