### ISSUE TITLE
How do I share a theme with another Statocles install?

### ISSUE THREAD

**Issue by cxw42** [preaction/Statocles#577]
Dumb question, but I've been through the POD docs related to themes and templates, and I can't find the answer.  Is there any way to send someone else a theme I've made other than a tarball of `theme/`?  I see that the default theme is in `share/` in the Statocles directory.  Is there support for making a CPAN module that embodies a theme in its `share/` files?  Perhaps `StatoclesX::Theme::...` or `Statocles::Contrib::Theme::...`?  Thanks!

**Comment by preaction** [comment]
There is, in theory, a way to do it. Ostensibly, the `::default` syntax was supposed to allow `My::Neat::Module` and have that distribution's `share/` directory be a theme. However, since that part of the theme system is going away in v2 (I'm skipping a version), I wouldn't use it.

For now, yes, tarballing up a theme directory is your best bet (or, if you want to be fancy, `git submodule` or `git subtree`). In the future, you will be able to make plugins that add directories to the template paths and layer themes on top of each other that way.

**Comment by cxw42** [comment]
OK - thanks for the quick response!  Should I leave this issue open for that future enhancement, or close it out?

**Comment by preaction** [comment]
I think we can close it: My goal is v2 before Advent (for Mojolicious.io), and I won't actually need to _do_ anything to get this feature when v2 releases, it's just how Mojolicious works (so, another way I vastly overcomplicated this whole thing and I should feel bad about it :wink:)
